import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className="h-[100vh] bg-slate-100   ">
      <body className=" h-[100vh] bg-slate-100 ">{children}</body>
    </html>
  );
}
